# Generated by Django 4.2 on 2023-05-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="quantity",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="ingredient",
            old_name="units",
            new_name="measurement_unit",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="slug",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(upload_to="recipes/media", verbose_name="картинка"),
        ),
    ]
