# Generated by Django 4.2 on 2023-05-13 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredient",
            options={
                "ordering": ("name",),
                "verbose_name": "ингредиент",
                "verbose_name_plural": "ингредиенты",
            },
        ),
        migrations.RemoveConstraint(
            model_name="ingredient",
            name="\nrecipes_ingredient_name is empty\n",
        ),
        migrations.RemoveConstraint(
            model_name="ingredient",
            name="\nrecipes_ingredient_measurement_unit is empty\n",
        ),
        migrations.AlterField(
            model_name="amountingredient",
            name="amount",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Добавьте что-нибудь!."
                    )
                ],
                verbose_name="Количество",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="measurement_unit",
            field=models.CharField(
                max_length=24, verbose_name="единицы измерения"
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.CheckConstraint(
                check=models.Q(("name__length__gt", 0)),
                name="recipes_ingredient_name пусто",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.CheckConstraint(
                check=models.Q(("measurement_unit__length__gt", 0)),
                name="recipes_ingredient_measurement_unit пусто",
            ),
        ),
    ]
