# Generated by Django 4.2 on 2023-05-05 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TagReceipt",
            new_name="TagRecipe",
        ),
    ]
