# Generated by Django 4.2 on 2023-05-03 07:29

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_rename_quantity_ingredient_amount_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IngredientReceipt",
            new_name="IngredientRecipe",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="image",
        ),
        migrations.AddField(
            model_name="recipe",
            name="image_url",
            field=models.ImageField(
                blank=True, null=True, upload_to=recipes.models.upload_to
            ),
        ),
    ]
