# Generated by Django 4.2 on 2023-05-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_rename_tagreceipt_tagrecipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="amount",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="measurement_unit",
            field=models.CharField(default="г", max_length=20),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="ingredient",
                to="recipes.ingredient",
                verbose_name="название ингридиента",
            ),
        ),
    ]
