# Generated by Django 4.2 on 2023-05-03 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0003_rename_ingredientreceipt_ingredientrecipe_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="image_url",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="description",
            new_name="text",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="duration",
        ),
        migrations.AddField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_favorited",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_in_shopping_cart",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор",
            ),
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="amount",
        ),
    ]
