# Generated by Django 4.2 on 2023-05-15 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_remove_amountingredient_ingredients_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="amountingredient",
            old_name="ingredient",
            new_name="ingredients",
        ),
    ]
