# Generated by Django 4.2 on 2023-05-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_alter_ingredient_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="amount",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
