# Generated by Django 4.2 on 2023-05-16 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0007_alter_favorite_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
            ],
            options={
                "verbose_name": "рецепт в списке покупок",
                "verbose_name_plural": "рецепты в списке покупок",
            },
        ),
        migrations.RenameModel(
            old_name="Favorite",
            new_name="Favorites",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="recipe",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="favorites",
            options={
                "verbose_name": "Избранный рецепт",
                "verbose_name_plural": "Избранные рецепты",
            },
        ),
        migrations.RemoveConstraint(
            model_name="favorites",
            name="recipes_favorite рецепт уже в избранном",
        ),
        migrations.AlterField(
            model_name="amountingredient",
            name="ingredients",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe",
                to="recipes.ingredient",
                verbose_name="Связанные ингредиенты",
            ),
        ),
        migrations.AlterField(
            model_name="amountingredient",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient",
                to="recipes.recipe",
                verbose_name="В каких рецептах",
            ),
        ),
        migrations.AddConstraint(
            model_name="favorites",
            constraint=models.UniqueConstraint(
                fields=("recipe", "user"),
                name="recipes_favorites рецепт уже в избранном",
            ),
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.AddField(
            model_name="carts",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_carts",
                to="recipes.recipe",
                verbose_name="рецепты в списке покупок",
            ),
        ),
        migrations.AddField(
            model_name="carts",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="владелец списка",
            ),
        ),
        migrations.AddConstraint(
            model_name="carts",
            constraint=models.UniqueConstraint(
                fields=("recipe", "user"),
                name="recipes_carts рецепт уже в списке",
            ),
        ),
    ]
