# Generated by Django 4.2.1 on 2023-05-19 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0011_alter_recipe_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Введите корректное время!"
                    ),
                    django.core.validators.MaxValueValidator(
                        6000, "Слишком долго ждать..."
                    ),
                ],
                verbose_name="время приготовления",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                upload_to="recipes/", verbose_name="изображение блюда"
            ),
        ),
    ]
