# Generated by Django 4.2 on 2023-05-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="email",
            field=models.EmailField(
                max_length=256, unique=True, verbose_name="адрес электронной почты"
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="username",
            field=models.CharField(
                max_length=256, unique=True, verbose_name="юзернейм"
            ),
        ),
    ]
