# Generated by Django 4.2 on 2023-05-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="myuser",
            options={
                "ordering": ("username",),
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
        migrations.AlterField(
            model_name="myuser",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="активирован"
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="last_name",
            field=models.CharField(max_length=256, verbose_name="фамилия"),
        ),
    ]
