# Generated by Django 4.2 on 2023-05-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_myuser_email_alter_myuser_password_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="myuser",
            name="\nusername is too short\n",
        ),
        migrations.AddConstraint(
            model_name="myuser",
            constraint=models.CheckConstraint(
                check=models.Q(("username__length__gte", 3)),
                name="username is too short",
            ),
        ),
    ]
